# TAKE HOME LAB EXERCISE - 01

-----------

**(1).Create a 1D array with 10 values in it and then convert the 1D array to 2D array ?**

In [5]:
import numpy as np

In [3]:
oned_arr=np.arange(31,51)[:10]
print("1D array:",oned_arr)
print("2D array:")
print(np.reshape(oned_arr,(2,5)))

1D array: [31 32 33 34 35 36 37 38 39 40]
2D array:
[[31 32 33 34 35]
 [36 37 38 39 40]]


-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [10]:
arr=np.array([4.454645,6645765767,89.6857659])
np.around(arr,3)

array([4.455e+00, 6.646e+09, 8.969e+01])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [3]:
x=np.arange(15)
print(x)
np.set_printoptions(threshold=5)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 ... 12 13 14]


---------------------

**(4). Take two arrays  `x` and `y` and Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [3]:
import numpy as np
x=np.arange(10).reshape(2,-1)
y=np.repeat(1,10).reshape(2,-1)
#using concatenate function
print(np.concatenate((x,y),axis=1))
#using stack function
np.hstack((x,y)).reshape((2,10))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). Consider the given array's and print the values which are common in both the arrays.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [40]:
x=np.array([1,2,3,2,3,4,3,4,5,6])
y=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(x,y)

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [5]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
np.array(list(filter(lambda i: i not in y, x)))               

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [15]:
X=np.arange(9).reshape(3,3)
print("input array: ")
print(X)
X[::-1]


input array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [27]:
X=np.arange(9).reshape(3,3)
print("input array:")
print(X)
X[:,::-1]


input array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [36]:
np.random.seed(10)
x = np.random.randint(20, size=10)
print(x.argsort().argsort())


[4 2 6 0 8 7 9 3 5 1]


--------------------

**(10). For the given numeric array print the rank array with same shape of numeric array.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [34]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(x.ravel().argsort().argsort().reshape(x.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [2]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3]).reshape(3,1)
x_2d-y_1d


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------